# PY03 - Data Science with Python: NumPy

Welcome to our first workshop in the ***Data Scientist's Toolkit*** series!
In this workshop we start to introduce our first Python library called NumPy. Libraries often contain a lot of useful in-built functions that have been pre-made for us to download. NumPy focuses on a lot of mathematical functionality, much of which we will omit or reserve for further work.


###  Table of Contents:

## 1) [What is NumPy](#win)
## 2) [NumPy arrays](#na)
## 3) [Mathematical Operations](#mo)
## 4) [Random Numbers](#rn)
## 5) [Complex Numbers](#cn)
## 6) [Other ways of making arrays](#oma)
## 7) [Matrix operations](#mo)



***But first:***

## Software Prerequisite
You will need the`NumPy`package for the workshop:

1. If you are using `conda` or you have installed `Anaconda` and launched the jupyter notebook from `Anaconda` 


In [1]:
#!conda install numpy

2. ***Otherwise***, `pip` is usually pre-installed if you are using Python 3. Use `pip` to install _NumPy_.

In [2]:
#!pip3 install numpy

## What Is _NumPy_?

_NumPy_ (Numerical Python), according to [numpy.org](https://numpy.org/devdocs/user/absolute_beginners.html)...

> ...is an open source Python library that’s used in almost **every field of science and engineering**. It’s the universal standard for working with **numerical data** in Python, and it’s at the core of the **scientific Python and PyData ecosystems**.

> ...The NumPy library contains **multidimensional array and matrix data structures** (you’ll find more information about this in later sections). It provides `ndarray`, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of **mathematical operations on arrays**. It adds powerful data structures to Python that guarantee **efficient calculations** with **arrays and matrices** and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

### Why bother with it?

#### Matrix Multiplication for $3 \times 3$ matrices

If you're familiar with matrices, you know that working out a matrix multiplication like this:

$$
\begin{bmatrix} 
5 & 7 & 2 \\
-2 & 3 & 6\\
5 & 8 & 1 
\end{bmatrix}
\begin{bmatrix} 
1 & 2 & 3 \\
-4 & 5 & 6\\
9 & 8 & 7 
\end{bmatrix}
$$

This takes a *lot* of time being written out, and since you're a human, you're bound to make mistakes somewhere. 

<div class="alert alert-block alert-info">
<b>Info:</b> To calculate a matrix multiplication, $AB = C$, you have to perform a multiplication for each component $ c_{ij} = a_{ik}b_{kj}$, where $A$ is an $n \times m$ matrix and $B$ is an $m \times p$ matrix
</div>



#### When $m, n, p$ are extremely high, it's going to get very painful. That's why we can use NumPy!


## Importing NumPy
Firstly, we will have to import NumPy, we can do this like so:

In [3]:
# Importing NumPy
import numpy as np

Notice we added: `as np` at the end of the import, this means that we don't have to write "`numpy`" before every numpy function, we can just write `np` instead. For example, if we wanted to write a square root, typing `np.sqrt(2)` is shorter than writing `numpy.sqrt(2)`

<div class="alert alert-block alert-info">
<b>Info:</b> It is common practice to import all necessary modules at the start of your code. If you see `ModuleNotFoundError: No module named 'numpy'`, it means you haven't installed it or it is not installed properly
</div>

## Making NumPy Arrays
Probably the most important feature from NumPy is the array. These are similar to lists although NumPy provides a great deal of functionality which we will be utilising in the workshops. Using this functionality enables you to perform various operations on large sets of data.

### Generating Arrays
There are many ways you can generate arrays. Some of these methods are displayed below.

#### [np.array](https://numpy.org/doc/1.19/reference/generated/numpy.array.html?highlight=array#numpy.array)
This command turns a list into a NumPy array.

In [4]:
# Generates an array [1 2 3]
x = np.array([1,2,3])
print("Array 1: ")
print(x)
# Generates a 2x3 array [[1 2 3] [4 5 6]]
x = np.array([[1,2,3],[4,5,6]])
print("\n Array 2: ")
print(x)

Array 1: 
[1 2 3]

 Array 2: 
[[1 2 3]
 [4 5 6]]


<div class="alert alert-block alert-danger">
<b>Warning:</b> x = np.array(1, 2, 3) is wrong while x = np.array([1, 2, 3]) is right, why do you think that's the case?
</div>

#### [np.linspace](https://numpy.org/doc/1.19/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace)
The function ````np.linspace```` has three arguments: startpoint, endpoint and number of points. The first number $0$ tells the kernel to start from $0$ while the second number tells it to end at $10$. The $5$ indicates the number of values in the array. The array will be created with an evenly spaced set of values starting from $0$ ending at $10$.

In [5]:
# Generates an array [0 2.5 5 7.5 10]
x = np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


#### [np.arange](https://numpy.org/doc/1.19/reference/generated/numpy.arange.html?highlight=arange#numpy.arange)
With ````np.arange```` three arguments are passed. The first, $0$ indicates the start point. The second argument, $11$ indicates the end point however it is not inclusive! The end point it actually the integer before the second argument; in this case $10$. The last argument indicates the spacing between each value. In this case the input is $1$ so as can be seen from the output each value is spaced accordingly.

In [6]:
# Generates an array [1 2 3 4 5 6 7 8 9 10]
x = np.arange(0,11,1)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


#### [np.zeros](https://numpy.org/doc/1.19/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros) and [np.ones](https://numpy.org/doc/1.19/reference/generated/numpy.ones.html?highlight=ones#numpy.ones)
If you want to produce arrays of a specific size these are probably your most useful choice. However, unless you're working entirely with zeros or ones you'll have to fill them first.

Both of these functions work in the exact same way: the number inside for the functions to produce the first two arrays simply specifies how many values are in your array. With `np.zeros` all these values are $0$ while with ````np.ones```` the values are $1$. 

For arrays with more dimensions than one, it **needs** to have another set of brackets with the size of each dimension seperated by commas. 

In [7]:
# Generates an array [0, 0.] in float64
x = np.zeros(2)
print("1st: ")
print(x)

# Generates an array [1 1 1] in integer
x = np.ones(3, int)
print("\nSecond: ")
print(x)

# Generates an 3x3 array of zeros
x = np.zeros((3,3))
print("\nThird: \n", x)

# Generates an 3x3 array of ones in integer
x = np.ones((3,3), int)
print("\nFourth: \n", x)

1st: 
[0. 0.]

Second: 
[1 1 1]

Third: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Fourth: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


#### Lists and Arrays?
As you can see by the output, the type of NumPy arrays and Python lists are different.

In [8]:
a = [1, 2, 3]
print("Type A: ", type(a))

b = np.array([1, 2, 3])
print("Type B: ", type(b))



Type A:  <class 'list'>
Type B:  <class 'numpy.ndarray'>


As well as their components

In [9]:
print("\nType A[0]", type(a[0]))
print("Type B[0]", type(b[0]))
# Or
print("Type B[0] (Alternatively)", b[0].dtype)


Type A[0] <class 'int'>
Type B[0] <class 'numpy.int32'>
Type B[0] (Alternatively) int32


#### Slicing
As you can see, you can call the individual components of the array:

In [10]:
# Creating a list 
x = [0,1,2,3,4,5]

# Slicing the list
print(x[3])

# Turning the list into an array
x = np.array(x)

# Slicing the array
print(x[3])

3
3


What about arrays with more dimensions? When slicing a 2D array you select by rows and columns. If you want to return a particular row then you simply specify`x[n]`, where`n`is the row index (remember Python starts counting from zero) and`x`is the array to be sliced. To select a particular column you would write ````x[:,n]````

Here the colon specifies that we are selecting all the rows and ````n```` selects a column. When picking a particular value you write`x[row index,column index]`

Arrays with more dimensions will have more indices but we will not discuss these. 

Presented here is an example of a $3\times3$ array. The slices of the array are placed in the same position as the array value they would return. If I had an array that looked something like: $$x =\begin{pmatrix} 1 & 0 & 3 \\ 4 & 5 & 0 \\ 9 & 2 & 0 \end{pmatrix}$$ then slices of each of these array values would look something like this: $$\begin{pmatrix} x[0,0] & x[0,1] & x[0,2] \\ x[1,0] & x[1,1] & x[1,2] \\ x[2,0] & x[2,1] & x[2,2] \end{pmatrix}$$

In [11]:
# Creates an array [[0 1 2] [3 4 5]]
x = np.array([[0,1,2],[3,4,5]])
print("The array:")
print(x)

# First row
print("\n First row:")
print(x[0])

# Second row
print("\n Second row:")
print(x[1])

# Second column
print("\nSecond column:")
      
print(x[:,1])

# First row, third column 
print("\nFirst row, third column:")
print(x[0,2])

The array:
[[0 1 2]
 [3 4 5]]

 First row:
[0 1 2]

 Second row:
[3 4 5]

Second column:
[1 4]

First row, third column:
2


## Mathematical Operations
Mathematical operations behave differently when applied to Python Lists than they do to NumPy Arrays. In fact many of the operations **cannot** be applied to lists or in the case of addition one needs to add another list. 

Examples are shown below.

In [12]:
# Defining a python list
x = [0, 1, 2, 3, 4, 5]

# Multiply list by 2
print("List multiplied by 2:", x*2)

# List added to a list
print("List added to a list:", x + x)

List multiplied by 2: [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
List added to a list: [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]


In [13]:
# Turns list into NumPy array
x = np.array(x)

# Multiply array by 2
print("Array multiplied by 2:", x*2)

# Adding 2 to array
print("Adding 2 to array:", x + 2)

# Adding array to array
print("Adding array to array:", x + x)

# Multiplying array to array (a.k.a squaring it)
print("Squaring an array:", x * x)

Array multiplied by 2: [ 0  2  4  6  8 10]
Adding 2 to array: [2 3 4 5 6 7]
Adding array to array: [ 0  2  4  6  8 10]
Squaring an array: [ 0  1  4  9 16 25]


As can be seen multiplying a Python list by a number will repeat the list that number of times.

Adding two lists simply attaches the second list to the end of the first. 

It can clearly be seen the same behaviour does not apply to arrays: Instead multiplying by a number multiplies each number in that array and adding a number to an array adds that number to each number in the array. Adding two arrays together results in values with the same position in that array being added together.

#### Useful Functions
Below is a list of useful functions which can be applied to arrays. 

In [14]:
# Creating an array
x = np.array([3,2,1,0])

# Finds the sum of all values in the array
print("Sum of the values:", np.sum(x))

# Finds the average of all values in the array
print("Average of the values:", np.mean(x))

# Sorts the values in the array into ascending order
print("Sorted values:", np.sort(x))

# Returns the maximimun value in the array
print("Maximum value:", np.max(x))

# Returns the minimum value in the array
print("Minimum value:", np.min(x))

# Returns the standard deviation
print("Standard deviation:", np.std(x))

# Returns the variance 
print("Variance:", np.var(x))

# Returns the size of the array
print("Size:", np.size(x))

# Returns the shape of the array
# which is a tuple of ints giving the lengths of the corresponding array dimensions
print("Shape:", np.shape(x))

# Multi-dimensional array
y = np.array([[1, 2, 3], [4, 5, 6,], [4, 5, 6,]])
print("Shape of y:", np.shape(y))

Sum of the values: 6
Average of the values: 1.5
Sorted values: [0 1 2 3]
Maximum value: 3
Minimum value: 0
Standard deviation: 1.118033988749895
Variance: 1.25
Size: 4
Shape: (4,)
Shape of y: (3, 3)


#### [np.roll](https://numpy.org/devdocs/reference/generated/numpy.roll.html?highlight=roll#numpy.roll)

This function is used to shift values along the array. For a one dimensional array you'll need two arguments: the array itself and then the shift. The shift determines how many indexes each value is moved along. A minus sign changes the direction. Example shifts are shown below.

Without NumPy, it's quite the __[challenge](https://leetcode.com/problems/rotate-array/)__

In [15]:
# Creates an array
x = np.array([1,2,3,4,5])

# Shifts array values by 1 to the right
print(np.roll(x,1))

# Shifts array values by 3 to the left
print(np.roll(x,-3))

[5 1 2 3 4]
[4 5 1 2 3]


#### [np.append](https://numpy.org/devdocs/reference/generated/numpy.append.html?highlight=append#numpy.append)

The first argument is an array. The second argument is the array to be attached to the end of the first.

In [16]:
# Creates arrays
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

# Attaches one array to the end of another
print(np.append(x,y))

[ 1  2  3  4  5  6  7  8  9 10]


#### [np.concatenate](https://numpy.org/devdocs/reference/generated/numpy.concatenate.html?highlight=concatenate#numpy.concatenate)

Similar to append but this will attach multiple arrays together. Note the need for an additional pair of brackets!

In [17]:
# Creates arrays
x = np.array([1,2,3,4,5])

y = np.array([6,7,8,9,10])

print(np.concatenate((x,y,x,y)))

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


#### [np.reshape](https://numpy.org/devdocs/reference/generated/numpy.reshape.html?highlight=reshape#numpy.reshape)

This function passes the array to be reshaped as the first argument, then in brackets the dimensions you want to reshape it to. Invalid choices for your dimensions will lead to an error.

In [18]:
# Creates array
x = np.array([1,2,3,4,5,6])

# Reshapes the array
print(np.reshape(x,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


### Mathematical Functions and Constants
In addition to the functions above, which are generally used on arrays, there are commonly used mathmatical functions and constants. Below are a few of these:

<div class="alert alert-block alert-info">
<b>Reminder:</b>  $e^0 = 1$ and thus $\ln1 = 0$
</div>


In [19]:
# Pi - NOT A FUNCTION
print("Pi:", np.pi)

# Square root function
print("Square root:", np.sqrt(9))

# Trigonometric functions (default input is in radians)
print("Sine:", np.sin(np.pi/2))
print("Cosine:", np.cos(0))

# Natural Constant e
print("e:", np.e)

# Exponential (input is the power)
print("Exponential:", np.exp(0))

# Natural logarithm ln
print("ln:", np.log(1))

# A complex number 1+2i 
print("Complex Number:", np.complex(1, 2))

Pi: 3.141592653589793
Square root: 3.0
Sine: 1.0
Cosine: 1.0
e: 2.718281828459045
Exponential: 1.0
ln: 0.0
Complex Number: (1+2j)


<ipython-input-19-b8b9736fca20>:21: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print("Complex Number:", np.complex(1, 2))


## Redefining Array Variables
By slicing one can redefine array variables. This is done by defining the slice of the array as what you wish it to be defined as. You can use loops to run over specific slices of an array in order to change the values of that array. Often it is useful to use the ````len```` function which returns the length of the array along one axis in order to loop over it. Examples are shown below.

In [20]:
# Creating a 3x3 array of zeros
x = np.zeros((3,3))

In [21]:
# Filling the diagonal components of the array 
x[0,0] = 1 
x[1,1] = 2
x[2,2] = 3

x

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [22]:
# Creates new array with 100 zero values
x = np.zeros(100)

In [23]:
# Here we loop over the length of the array using len(x) to find the length of x
for i in range(len(x)):
    # Redfines current value of the array as current value of i
    x[i] = i

x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

### Random Numbers 
NumPy can be used to generate random numbers. Two functions for this are shown below.

#### [np.random.random](https://numpy.org/devdocs/reference/random/generated/numpy.random.random.html?highlight=random#numpy.random.random)

This returns random float numbers from half-open interval $[0.0, 1.0)$ (Includes 1.0, not 0.0)

In [24]:
# Generates a random number from 0 to 1, exclusively
print(np.random.random())

# Generate 6 random numbers from 0 to 1, exclusively
print(np.random.random(6))

# Generates an array of random numbers for a 3x3 array
print(np.random.random((3,3)))

0.03281437803427134
[0.12574176 0.86896629 0.48131642 0.78702474 0.0821737  0.95997731]
[[0.99206911 0.1920051  0.70333141]
 [0.9622875  0.75122846 0.86064653]
 [0.61822617 0.04816802 0.34898689]]


#### [np.random.randint](https://numpy.org/devdocs/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint)

This returns random integers in a specified range. The first value is the lowest possible value while the second input is one higher than the highest possible value. The third input is the dimensions of an array (in brackets) to be filled with random integers. 

In [25]:
# Generates a random number from 1 to 6
print(np.random.randint(1, 7))

# Generates a 3x3 array of random integers from 1 to 6
print(np.random.randint(1, 7, (3,3)))

# 9x4 array of random integers from 10 to 25
print(np.random.randint(10, 26, (9,4)))

3
[[4 2 3]
 [6 1 5]
 [5 6 4]]
[[20 12 15 13]
 [21 12 14 15]
 [23 14 18 21]
 [16 15 19 25]
 [20 25 12 18]
 [10 13 11 23]
 [15 11 19 14]
 [25 21 24 12]
 [13 12 21 15]]


## Further Knowledge:



### Complex Numbers 
If you wish to fill arrays with complex numbers you need to pass an additional argument when creating the array (If you are converting a list with a complex number already inside you need not do this). The problem is the data type of values in arrays you create is normally float so this leads to an error when trying to redefine it as a complex number as the complex number can't be converted to a float. To resolve this use the additional argument ````dtype=complex```` when generating your array.

In [26]:
# Generates a 3x3 array of zeros
x = np.zeros((3,3))

# Trying to convert a value to a complex number
x[0,0] = 1 + 1j

TypeError: can't convert complex to float

In [27]:
# Generates a 3x3 array of zeros
x = np.zeros((3,3),dtype=complex)

# Trying to convert a value to a complex number
x[0,0] = 1 + 1j

# Outputs result
print(x)

[[1.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


### Other Ways of Making Arrays
In addition to the functions above there are more functions that can be used to create arrays.

#### [np.logspace](https://numpy.org/devdocs/reference/generated/numpy.logspace.html?highlight=logspace#numpy.logspace)

This is similar to ````np.linspace```` however this works on a logarithmic scale (base $10$ by default). The first argument indicates the starting power, the second argument indicates the highest power and the third argument is the number of points. These points are evenly spaced on the logarithmic scale.

In [28]:
# Creates an array of values using the logarithmic scale (base 10)
x = np.logspace(0,3,4)
print(x)

[   1.   10.  100. 1000.]


#### [np.meshgrid]()
This is a way of generating a set of 2D arrays from two already existing arrays. Usually this technique is used when generating a 2D grid of points.

In [29]:
# Defining two arrays of different lengths
x = np.linspace(0,10,11)
print("x =", x)

y = np.linspace(0,5,6)
print("y =", y)

# Generating a 2D grid
x2D, y2D = np.meshgrid(x,y)

# Outputting the 2D arrays
print(x2D)
print(y2D)

x = [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
y = [0. 1. 2. 3. 4. 5.]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


<a id = "mo"></a>

## More Mathematical Operators
Arrays in NumPy are often used to represent mathematical objects called vectors and matrices. Arrays with one dimension can represent vectors while arrays with two dimensions can be used to represent matrices. One can also use arrays with more dimensions. Multiplying arrays together multiplies values in equivalent positions in each array together. Those of you taking maths courses will know this is not how vectors behave! The same is true of matrices. Luckily NumPy has in-built functions that allow us to properly apply operations to vectors and matrices. 
### Absolute Value of a Vector
The magnitute of a vector is defined as: $$|\textbf{a}| = \sqrt{a^{2}_{1} + a^{2}_{2} + a^{2}_{3}} $$ 

In [30]:
# Creates a vector [4 3 0]
a = np.array([4,3,0])

# Magnitude of the vector
print(np.linalg.norm(a))

5.0


### Scalar/Dot Product
The scalar product between two vectors is defined as: $$\textbf{a}\cdot\textbf{b} = \sum_{i} a_i b_i, $$
$$\begin{pmatrix} a_1 \\ a_2 \\a_3 \end{pmatrix} \cdot \begin{pmatrix} b_1 \\ b_2 \\b_3 \end{pmatrix} = a_1 b_1 + a_2 b_2 + c_1 c_2, $$
$$\begin{pmatrix} 4 \\ 3 \\-1 \end{pmatrix} \cdot \begin{pmatrix} 1 \\ 3 \\ 2  \end{pmatrix} = (4\times 1) + (3\times 3)+(-1\times 2) = 11.$$

In [31]:
# Creates arrays/vectors a and b
a = np.array([4,3,-1])
print("a =",a)

b = np.array([1,3,2])
print("b =",b)

# Dot product between the two vectors
print("a.b =", np.dot(a,b))

a = [ 4  3 -1]
b = [1 3 2]
a.b = 11


### Matrix Multiplication 
Matrix multiplication is in effect a dot product between two matrices and so uses ````np.dot````. Matrix multiplication for a matrix **A** and **B** works as follows: $$ \textbf{A} \textbf{B} = \sum_{j} a_{ij} b_{jk} $$ $$ \begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11}+a_{12}b_{21} & a_{11}b_{12}+a_{12}b_{22} \\ a_{21}b_{11}+a_{22}b_{21} & a_{21}b_{12}+a_{22}b_{22} \end{pmatrix} $$ $$ \begin{pmatrix} 4 & 0 \\ 0 & 2 \end{pmatrix} \begin{pmatrix} 0 & 1 \\ 3 & 2 \end{pmatrix} = \begin{pmatrix} (4\times 0)+(0\times 3) & (4\times 1)+(0\times 2) \\ (0\times 0)+(2\times 3) & (0\times 1)+(2\times 2) \end{pmatrix} = \begin{pmatrix} 0 & 4 \\ 6 & 4 \end{pmatrix}$$

In [32]:
# Creates arrays/vectors a and b
A = np.array([[4,0],[0,2]])
print(A)

B = np.array([[0,1],[3,2]])
print(B)

# Dot product between the two vectors
print(np.dot(A,B))

[[4 0]
 [0 2]]
[[0 1]
 [3 2]]
[[0 4]
 [6 4]]


### Vector/Cross Product 
The vector product between two vectors is defined as: $$\begin{pmatrix} a_1 \\ a_2 \\a_3 \end{pmatrix} \times \begin{pmatrix} b_1 \\ b_2 \\b_3 \end{pmatrix} = \begin{pmatrix} a_2 b_3 - a_3 b_2 \\ a_3 b_1 - a_2 b_1 \\ a_1 b_2 - a_2 b_1 \end{pmatrix}, $$ $$\begin{pmatrix} 1 \\ 0 \\0 \end{pmatrix} \times \begin{pmatrix} 0 \\ 1 \\ 0 \end{pmatrix} = \begin{pmatrix} (0\times 0) - (0\times 1) \\ (0\times 0) - (0\times 0) \\ (1\times 1) - (0\times 0) \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix}. $$

In [33]:
# Creates arrays/vectors a and b
a = np.array([1,0,0])
print("a =",a)

b = np.array([0,1,0])
print("b =",b)

# Cross product between the two vectors
print("a x b =", np.cross(a,b))

a = [1 0 0]
b = [0 1 0]
a x b = [0 0 1]


### Tensor/Outer Product
The tensor/outer product has between two vectors is defined below: $$ \textbf{a}\otimes\textbf{b}=a_i b_j = c_{ij} $$
$$ \begin{pmatrix} a_1 \\ a_2 \\ a_3 \end{pmatrix} \otimes \begin{pmatrix} b_1 \\ b_2 \\ b_3 \end{pmatrix} = \begin{pmatrix} a_1 b_1 & a_1 b_2 & a_1 b_3 \\ a_2 b_1 & a_2 b_2 & a_2 b_3 \\ a_3 b_1 & a_3 b_2 & a_3 b_3 \end{pmatrix} $$ $$ \begin{pmatrix} 0 \\ 2 \\ 1 \end{pmatrix} \otimes \begin{pmatrix} 5 \\ 0 \\ 1 \end{pmatrix} = \begin{pmatrix} 0\times 5 & 0\times 0 & 0\times 1 \\ 2\times 5 & 2\times 0 & 2\times 1 \\ 1\times 5 & 1\times 0 & 1\times 1  \end{pmatrix}  = \begin{pmatrix} 0 & 0 & 0 \\ 10 & 0 & 2 \\ 5 & 0 & 1 \end{pmatrix} $$ 

In [34]:
# Creates arrays/vectors a and b
a = np.array([0,2,1])
print("a =",a)

b = np.array([5,0,1])
print("b =",b)

# Outer product between the two vectors
print(np.outer(a,b))

a = [0 2 1]
b = [5 0 1]
[[ 0  0  0]
 [10  0  2]
 [ 5  0  1]]


### Matrix Inversion
One can find the inverse of a matrix as follows.

In [35]:
# Creates an matrix 
x = np.array([[0,1],[-1,0]])
print(x)

# Inverses the matrix
print(np.linalg.inv(x))

[[ 0  1]
 [-1  0]]
[[-0. -1.]
 [ 1.  0.]]


### Eigenvalues 
The eigenvalues of a matrix may be found as follows:

In [36]:
# Creates a matrix 
x = np.array([[0,1,2],[1j,1+1j,0],[2j,0,2+2j]])
print(x)

print(np.linalg.eigvals(x))

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+1.j 1.+1.j 0.+0.j]
 [0.+2.j 0.+0.j 2.+2.j]]
[-0.93853719-0.93853719j  2.79483214+2.79483214j  1.14370505+1.14370505j]


These are just a few examples of what can be done with NumPy and there are many more not covered in the workshops. If you ever want to look for a function for a mathematical operation not covered here you can always try searching it online. If NumPy doesn't have it you may need to look at another package like SciPy or simply code it yourself.